### ISSUE TITLE
Fabric.io

### ISSUE THREAD

**Issue by Sm200** [ExploiTR/DeAutherDroid#5]
while building apk file android studio throw a error saying fabric.io  invalid build secret

**Comment by ExploiTR** [comment]
I collect information about just 
> **How much people are using my app & Application crash logs**

So, Fabric helps me for that.

---------------------------------------------------------------------------------------------------------------

The error is thrown because I've replaced my own valid `apiSecret` for authentication with Fabric (some 76e5tfg764h53e4576587hr43e865 ) with invalid one (some ###########################).

As you will be able to see in the file located at `\Studio\DeAutherWebGUI\app\fabric.properties`

----------------------------------------------------------------------------------------------------------------

What you can do is : 

 - Register at [Fabric](fabric.io) , get your own `apiSecret` then replace the one in `fabric.properties` file mentioned above. Then, you also will be able to see users for `your own` build and crash logs too.

 - Or, delete the `fabric.properties` file mentioned above from it's location. Turn the variable `isFinalBuild` (*public static final boolean isFinalBuild*) which is in *MainActivity.java* to **false** (This won't trigger fabric calls). Now, find this         ``` <meta-data
            android:name="io.fabric.ApiKey"
            android:value="$#########################@$$$$" /> ```  in *AndroidManifest.xml* & **remove** this line.

-----------------------------------------------------------------------------------------------------------------

I think above informations are fine to help you out.
